# 此YAML文件用于在集群内容暴露Sentinel部署，以供其它应用访问和调用。
apiVersion: v1
kind: Service
metadata:
  name: {{ template "redis-ha.fullname" . }}-sentinel
  labels:
    name: {{ template "redis-ha.name" . }}-sentinel-svc
    role: service
  {{ include "labels.standard" . | indent 4 }}
spec:
  ports:
    - port: 26379
      targetPort: 26379
  selector:
    app: {{ template "redis-ha.name" . }}
    release: "{{ .Release.Name }}"
    redis-role: "sentinel"
