# 此YAML配置文件为定义了redis master的服务，此服务暴露6379端口，以供在集群中使用.
apiVersion: v1
kind: Service
metadata:
  name: {{ template "redis-ha.fullname" . }}-master-svc
  labels:
  {{ include "labels.standard" . | indent 4 }}
  annotations:
  {{ toYaml .Values.servers.annotations | indent 4 }}
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: {{ template "redis-ha.name" . }}
    release: "{{ .Release.Name }}"
    redis-node: "true"
    redis-role: "master"
  type: "{{ .Values.servers.serviceType }}"

