# 如果rbac.create的值为true，则此YAML文件将会定义名为{{template “redis-ha.fullname” .}}一个角色，
# 此角色拥有获取、列示和修改pods的权限。

  {{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "redis-ha.fullname" . }}
  labels:
  {{ include "labels.standard" . | indent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - patch
  {{- end -}}
